Personnel security:
  "Personnel security checks":
    requirements: Consumers should be content with the level of security screening conducted on service provider staff with access to their information or with ability to affect their service.
    filters: Consumers should be content with the level of security screening conducted on service provider staff with access to their information or with ability to affect their service.
    hint: "What kind of personnel security do you apply to staff who have access to the service? Choose all that apply."
    dependsOnLots: SaaS, PaaS, IaaS, SCS
    assuranceApproach:
    fields:
      - type: checkbox
        label: "Security clearance national vetting (SC)"
      - type: checkbox
        label: "Baseline personnel security standard (BPSS)"
      - type: checkbox
        label: "Background checks in accordance with BS7858:2012"
      - type: checkbox
        label: "Employment checks"
    validationNotAnswered: "This question requires an answer."
