- Page 0:
    name: Service type
    file: service/service-details.yml
- Page 1:
    name: Service type
    file: service/service-type-IaaS.yml
- Page 2:
    name: Service type
    file: service/service-type-SaaS.yml
- Page 3:
    name: Service type
    file: service/service-type-SCS.yml
- Page 4:
    name: Service description
    file: service/service-description.yml
- Page 5:
    name: Features and benefits
    file: service/features-and-benefits.yml
- Page 6:
    name: Service definition
    file: service/service-definition.yml
- Page 7:
    name: Terms and conditions
    file: service/terms-and-conditions.yml
- Page 8:
    name: Pricing
    file: service/pricing.yml
- Page 9:
    name: Open standards
    file: service/open-standards.yml
- Page 10:
    name: Support
    file: service/support.yml
- Page 11:
    name: Onboarding and offboarding
    file: service/onboarding-and-offboarding.yml
- Page 12:
    name: Analytics
    file: service/analytics.yml
- Page 13:
    name: Cloud features
    file: service/cloud-features.yml
- Page 14:
    name: Provisioning
    file: service/provisioning.yml
- Page 15:
    name: Open source
    file: service/open-source.yml
- Page 16:
    name: Code libraries
    file: service/code-libraries.yml
- Page 17:
    name: API access
    file: service/api-access.yml
- Page 18:
    name: Networks and connectivity
    file: service/networks-and-connectivity.yml
- Page 19:
    name: Access
    file: service/access.yml
- Page 20:
    name: Certifications
    file: service/certifications.yml
- Page 21:
    name: Identity standards
    file: service/identity-standards.yml
- Page 22:
    name: Data storage
    file: service/data-storage.yml
- Page 23:
    name: Data-in-transit protection
    file: service/security/data-in-transit-protection.yml
- Page 24:
    name: Asset protection and resilience
    file: service/security/asset-protection-and-resilience.yml
- Page 25:
    name: Separation between consumers
    file: service/security/separation-between-consumers.yml
- Page 26:
    name: Governance
    file: service/security/governance.yml
- Page 27:
    name: Configuration and change management
    file: service/security/configuration-and-change-management.yml
- Page 28:
    name: Personnel security
    file: service/security/personnel-security.yml
- Page 29:
    name: Secure development
    file: service/security/secure-development.yml
- Page 30:
    name: Supply-chain security
    file: service/security/supply-chain-security.yml
- Page 31:
    name: Authentication of consumers
    file: service/security/authentication-of-consumers-to-management-interfaces-and-within-support-channels.yml
- Page 32:
    name: Identity and authentication
    file: service/security/identity-and-authentication.yml
- Page 33:
    name: External interface protection
    file: service/security/external-interface-protection.yml
- Page 34:
    name: Secure service administration
    file: service/security/secure-service-administration.yml
- Page 35:
    name: Audit information provision to consumers
    file: service/security/audit-information-provision-to-consumers.yml
- Page 36:
    name: Secure use of the service by the customer
    file: service/security/secure-use-of-the-service-by-the-customer.yml
