-
  name: Essentials
  editable: True
  questions:
    - termsOfParticipation
    - termsAndConditions
    - davidKershaw
    - readUnderstoodGuidance
    - understandTool
    - understandHowToAskQuestions
    - proofOfClaims
    - permanentMemberOfStaff
    - skillsAndResources
    - accuratelyDescribed
    - canProvideServices
-
  name: Grounds for mandatory exclusion
  editable: True
  questions:
    - conspiracyCorruptionBribery
    - fraudAndTheft
    - terrorism
    - organisedCrime
-
  name: Grounds for discretionary exclusion
  editable: True
  questions:
    - taxEvasion
    - environmentalSocialLabourLaw
    - bankrupt
    - graveProfessionalMisconduct
    - distortingCompetition
    - conflictOfInterest
    - distortedCompetition
    - significantOrPersistentDeficiencies
    - seriousMisrepresentation
    - witheldSupportingDocuments
    - influencedContractingAuthority
    - confidentialInformation
    - misleadingInformation
    - mitigatingFactors
    - unspentTaxConvictions
    - GAAR
    - mitigatingFactors2
-
  name: Working with government
  editable: True
  questions:
    - MI
    - canProvideFromDayOne
    - evidence
    - environmentallyFriendly
    - consistentDelivery
    - continuousProfessionalDevelopment
    - customerSatisfactionProcess
    - permanentMemberOfStaff
    - equalityAndDiversity
-
  name: Working with digital
  editable: True
  questions:
    - technologyCodesOfPractice
    - serviceStandard
    - ongoingEngagement
    - transparentContracting
    - publishContracts
    - safeguardOfficialInformation
    - safeguardPersonalData
    - cyberEssentials
    - cyberEssentialsPlus
-
  name: About you
  editable: True
  questions:
    - primaryContact
    - primaryContactEmail
    - nameOfOrganisation
    - registeredAddress
    - tradingStatus
    - tradingStatusOther
    - tradingNames
    - firstRegistered
    - firstRegisteredCountry
    - companyRegistrationNumber
    - registeredVATNumber
    - establishedInTheUK
    - appropriateTradeRegisters
    - appropriateTradeRegistersNumber
    - licenceOrMemberRequired
    - licenceOrMemberRequiredDetails
    - organisationSize
    - subcontracting
    - contactNameContractNotice
    - contactEmailContractNotice
-
  name: LEFTOVERS
  editable: True
  questions:
    - skillsAndCapabilityAssessment
    - civilServiceValues
    - userNeeds
    - changesInNeeds
    - framingNeeds
    - freeAndOpenData
    - bespokeSystemInformation
    - openStandardsComponents
    - governmentsDesire
    - reusePurchasedAssets
    - governmentSecurityPrinciples
    - openStandardsPrinciples
    - openSourceLicence
    - incentives
    - safeguardData
    - hideGovernment
    - employmentAgency
