-
  name: Apply to an opportunity
  editable: True
  description: |
    Buyers will use the information suppliers provide here to create a shortlist.
  questions:
    - respondToEmailAddress
    - essentialRequirements
    - niceToHaveRequirements
    - availabilityOutcomes
    - availabilitySpecialists
    - dayRate
