id: trainingDetailType
question: Type of training
hint: 100 characters maximum
type: text
optional: true
depends:
  - "on": "lot"
    being:
      - training
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
  -
    name: under_character_limit
    message: "Your training type needs to be 100 characters or less."
empty_message: Add type of training
