question: Product manager
name: Product manager
depends:
  - "on": lot
    being:
      - digital-specialists
type: multiquestion
any_of: specialist
questions:
  - productManagerLocations
  - productManagerDayRate

empty_message: You haven't added a product manager
