question: Security
name: Security
optional: true
depends:
  - "on": lot
    being:
      - digital-outcomes
type: multiquestion
any_of: capability
questions:
  - securityTypes

empty_message: You haven't added any security capabilities

hint: Minimise the chance of data or information systems security breaches. Ensure information is protected against unauthorised or unintended access. Put systems in place to prevent data destruction or disruption.
